.TH "Répertoire de référence de Drawall/" 3 "Samedi Juillet 6 2013" "Version 1.0" "Drawall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de Drawall/ \- 
.SH SYNOPSIS
.br
.PP
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBdrawall\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBdrawall\&.h\fP"
.br
.RI "\fIFichier d'en-tête de la bibliothèque\&. \fP"
.ti -1c
.RI "fichier \fBparams\&.h\fP"
.br
.in -1c
