.TH "bug" 3 "Samedi Juillet 6 2013" "Version 1.0" "Drawall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bug \- Liste des bogues 
.IP "\fBMembre \fBDrawall::Position\fP \fP" 1c
Ne fonctionne pas dans le sketch\&.  
.IP "\fBMembre \fBDrawall::setPosition\fP (Position position)\fP" 1c
Ne fonctionne pas sur le sketch\&. 
.PP

